Insert Into Prompts (question,createdAt,updatedAt) Values ("Describe your happiest childhood memory?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is a popular song that you enjoy (and why do you like it)?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is one of your favorite songs from your childhood?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Who is the one friend you can always rely on?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is the biggest accomplishment in your personal life?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is the biggest accomplishment in your professional life?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is your favorite memory of your father (or stepfather)?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is your favorite memory of your mother (or stepmother?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Describe your favorite pet (or former pet)?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("List 10 hobbies and activities that bring you joy?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What promptsis a mistake that I’ve made, which ultimately led to a positive experience?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Describe a family tradition that you are most grateful for.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Who is a teacher or mentor that has made an impact on your life and how did they help you?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What do you like the most about your town or city?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Describe your favorite location in your house and why you like it.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is one something you’ve learned this week that you're thankful for?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Who made you smile in the past 24 hours and why?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is a recent purchase that has added value to your life?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is the biggest lesson you learned in childhood?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("List 10 ways you can share your gratitude with other people in the next 24 hours.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Describe your favorite smell.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Describe your favorite sound.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Describe your favorite sight.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Describe your favorite taste.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Describe your favorite sensation.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("How can you pamper yourself in the next 24 hours?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Name and write about someone you’ve never met, but who has helped your life in some way.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("How is your life more positive today than it was a year ago?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What do other people like about you?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("List 10 skills you have that most people don’t possess.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Describe the last time someone helped you solve a problem at work.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is your favorite part of your daily routine?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is a great book you’ve recently read?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is your favorite holiday and why do you love it?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is your favorite T.V. show and why do you love it?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is your favorite movie and why do you love it?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is your favorite way to enjoy nature? (i.e. walking in the woods, sitting on the beach, or hiking in the mountains, etc.)",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Write about a recent obstacle you faced and how you overcame it.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Describe a favorite pet and what you love(d) about it.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("List 10 things you are looking forward to in the next year.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What do you love most about your country?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is your favorite food you love to indulge in?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Write about someone who makes your life better.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("If you’re single, what is your favorite part about being single? Or if you’re married, what is your favorite part about being married?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is today’s weather and what is one positive thing you can say about it?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Describe a weird family tradition that you love?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("When was the last time you had a genuine belly laugh and why was it so funny?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What body part or organ are you most grateful for today? (e.g., your eyes because you got to see a new movie)",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is a major lesson that you learned from your job?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("List 10 items that you take for granted, which might not be available to people in other parts of the world (i.e. Clean water, electricity, etc.)",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Write about a recent time when a stranger did something nice for you.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is the hardest thing you’ve had to do, which led to a major personal accomplishment?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is one aspect of your health that you’re more grateful for?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Who can you count on whenever you need someone to talk to and why?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Describe the last time you procrastinated on a task that wasn’t as difficult as you thought it would be.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is your favorite habit and why it is an important part of your daily routine?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Describe a “perfect day” that you recently had.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is a favorite country that you’ve visited?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Describe a funny YouTube video that you recently watched.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("List 10 qualities do you like about yourself.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is one thing you look forward to enjoying each day after work?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What was something you did for the first time recently?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is one lesson you learn from rude people?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("When was the last time you had a great nap where you awoke feeling fully refreshed?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Shower or bath? Which do you prefer and why?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Write about a time where you felt courageous.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What are a few ways you can appreciate your health whenever you’re sick?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is a favorite drink that you like to enjoy each day?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Who has forgiven you for a mistake you’ve made in the past?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("List 10 things you have now that you didn’t have 5 years ago.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What aspects of your job do you enjoy the most?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is something positive you can learn from one of your negative qualities? (i.e. Being anxious means you’re really good at planning things out.)",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What are a few aspects of modern technology that you love?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is a great recipe you’ve prepared that others rave about?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Describe a recent time when you truly felt at peace.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is your favorite quote or a bit of wisdom that you like to frequently share with others?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is your favorite sports team?  Describe a cherished memory you have when cheering for this team.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Are you a morning person or a night owl?  What do you love most about this part of the day?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is the last thank you note you’ve received and why?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("List 10 of your favorite possessions.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is a small win that you accomplished in the past 24 hours?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Describe one thing that you like about your daily commute to work?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is a personal viewpoint that positively defines you as a person?  ",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Describe an experience that was painful, but made you a stronger person.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is your favorite season and what do you like about it?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What makes you beautiful?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What are you most looking forward to this week?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Describe a small, everyday thing that you enjoy with a special person in your life.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is an app or piece of technology that you use every day which adds value to your life?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("List 10 things you like about your job or workplace.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Describe a favorite outfit and why you feel great when wearing it.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What activity do you enjoy most when alone?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What activity do you enjoy when with others?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Describe your oldest friend. What do you like most about this person?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("How have you recently cared for your physical wellbeing?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("How have you recently cared for your mental wellbeing?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("When you were a child, what did you want to be when you grew up?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is your favorite charity and why do you support it?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Write about a challenging person in your life (i.e. someone you frequently disagree with) and the qualities you like about this person.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("List 10 things you like the most about your country?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What book are you most grateful for having read?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What hobbies (or activities) would you miss if you could no longer do them?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is something you love(d) about your father (or step-father)?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is something you love(d) about your mother (or step-mother)?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Where was your last vacation? Describe what you did there.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is something that comes easily to you, but is challenging for others?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is something that you’ve recently fixed?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Describe something positive in your life that you didn’t have five years ago.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What makes you happy when you’re feeling down.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("List 10 major life accomplishments that you’re proud to have achieved.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What artist, musician or author are you most grateful for?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What do you love most about the current season?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What gift did you enjoy receiving in the past year?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What freedoms are you most grateful for?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("Look around the room and list all the items that you’re grateful for.",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What fear are you currently facing?  How can you use this fear to your advantage?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is your top goal?  Why is this goal important to you?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What is your favorite emotion to feel?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("What makes you happy to be alive?",NOW(),NOW());
Insert Into Prompts (question,createdAt,updatedAt) Values ("List 10 things that you hope will happen in the next year.",NOW(),NOW());